### PR TITLE
fix: Update _FilterBackendProtocol to be compatible with latest pyright

### PR DESCRIPTION
**Pull request by last-partizan**
After latest changes to pyright, old code isn't working with django-filter. https://github.com/microsoft/pyright/issues/5027#issuecomment-1598170551

Instead of adding types to django-filter, we modify this to allow any QS

We also removing schema-related methods from protocols, becouse they're already deprecated in django-filters.

Other options that i have considered - adding type-var bound types to django-filter package, but that would be harder to implement, so i think relaxing requirements here is better.

### CODE REVIEW

**Comment by last-partizan** [comment]
Hmm, maybe it's better to leave it as is, because it adds more problems than solves.

**Comment by last-partizan** [comment]
https://github.com/microsoft/pyright/discussions/5350

I created discussion here.

@sbdchd if you have an idea how to solve this problem with django-filter, please take a look.

Btw, why do we have MongoQuerySet here? it's tempting for me to just remove it. But obviously it's needed for some case. 
I'm using mongoengine myself, but with `django-mongoengine` and don't type check that parts of code, because they're very old.

**Comment by sbdchd** [comment]
yeah the mongo query stuff is really a kludge (not that the rest of the library isn't lol)

I needed it for the codebase at my previous employer -- I don't use mongo + Django rest framework anymore though

**Comment by last-partizan** [comment]
Let's remove it then.

If someone needs it again, we can add protocol for this.

Btw, circleCI is broken or something? Can we replace it with github-ci? I was trying to migrate `django-types` to github actions in my repo, it you're interested - i can finish it and create PR. For both projects.

**Comment by last-partizan** [comment]
Hi, can we get this merged?

**Comment by sbdchd** [comment]
not sure what's up with circle, manually merged it!

Thank you!!

**Comment by last-partizan** [comment]
Thanks! what do you think about migrating to github-ci?

**Comment by sbdchd** [comment]
yeah I really need to but it's so not fun to do 😭

**Comment by last-partizan** [comment]
I'll create PR with changes :)

**Pull request merged**
