### PR TITLE
Add queryset and kwargs to @action

### PR DESCRIPTION
**Pull request by last-partizan**
I've added queryset, and kwargs, becouse it allows to overrider any, even user-defined attrs.

### CODE REVIEW

**Review by sbdchd — APPROVED** [review]
Interesting, didn't know about the overriding user params functionality.

**Comment by sbdchd** [comment]
Looks good, I got CI running, it's angry:

```
ERROR: /home/circleci/project/rest_framework-stubs/decorators.pyi Imports are incorrectly sorted.
ERROR: /home/circleci/project/typings/rest_framework/decorators.pyi Imports are incorrectly sorted.
```

**Comment by last-partizan** [comment]
I couldn't resolve this myself.

I tried installing venv, updating poetry.lock (becouse it doesn't work with current version of poetry) and using isort/black from `.venv`, isort are doing this changes, which are triggering black reformatting it back to single line.

```diff
diff --git a/typings/rest_framework/decorators.pyi b/typings/rest_framework/decorators.pyi
index d3a6b71..3f56282 100644
--- a/typings/rest_framework/decorators.pyi
+++ b/typings/rest_framework/decorators.pyi
@@ -1,4 +1,15 @@
-from typing import Any, Callable, Dict, List, Mapping, Optional, Sequence, Type, TypeVar, Union
+from typing import (
+    Any,
+    Callable,
+    Dict,
+    List,
+    Mapping,
+    Optional,
+    Sequence,
+    Type,
+    TypeVar,
+    Union,
+)

 from django.db.models import QuerySet
 from django.http.response import HttpResponseBase
```


Could you please merge it as is and sort imports afterwards?

**Comment by sbdchd** [comment]
Oh yeah, I think this project is using a really really old version of poetry, I'll merge and figure out the upgrade / lint issues

**Pull request merged**
